
name: ECS Service Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Continous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Setup AWS Actions
        uses: actions/checkout@v2

      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Deploy Amazon ECS task definition
        run: copilot deploy -e test